# Dockerfile.dev
FROM node:20

WORKDIR /app

COPY package*.json ./

# COPY ./node_modules /app/node_modules
# COPY . .

# Install all deps including devDependencies
# RUN npm install

# Copy source code

# Prisma generate (only if needed in dev)
# RUN npx prisma migrate dev

EXPOSE 3000
EXPOSE 5555

CMD ["npm", "run", "dev"]
